#!/bin/bash

REPO_ROOT="$(git rev-parse --show-toplevel)"

source "$REPO_ROOT/.githooks/utils.sh"

prev_head=$1
new_head=$2
branch_checkout=$3

if [ "$branch_checkout" = "1" ]; then
    print_info "🔄 Running post-checkout checks..."
    echo

    if git diff --name-only "$prev_head" "$new_head" | grep -q "pyproject.toml\|uv.lock"; then
        print_action "Detected changes in dependencies. Installing packages"
        if ! maybe_install_packages; then
            print_warning "Failed to install dependencies after checkout"
        fi
    fi
    echo

    print_success "🎉 Post-checkout checks completed!"
fi

exit 0
